language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  # - yarn inspect
  - yarn test:ci
  - yarn build # Make sure the app can be built without errors

after_script:
  - yarn ocular coverage/clover.xml

sudo: false
